// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main (
 input [1:0] v6990c9,
 output [1:0] vd55eb8,
 output [0:5] vinit
);
 wire [0:1] w0;
 assign w0 = v6990c9;
 assign vd55eb8 = w0;
 assign vinit = 6'b000000;
endmodule

