// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main (
 input ve946d7,
 output vb54991,
 output [0:6] vinit
);
 wire w0;
 assign vb54991 = w0;
 assign w0 = ve946d7;
 assign vinit = 7'b0000000;
endmodule

