// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main (
 output vb54991,
 output vfa7327,
 output vdb2924,
 output v7762e3,
 output vdf58cb,
 output v8b3791,
 output v093df3,
 output v7a8754
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 assign vb54991 = w0;
 assign vfa7327 = w1;
 assign vdb2924 = w2;
 assign v7762e3 = w3;
 assign vdf58cb = w4;
 assign v8b3791 = w5;
 assign v093df3 = w6;
 assign v7a8754 = w7;
 assign w1 = w0;
 assign w2 = w0;
 assign w2 = w1;
 assign w3 = w0;
 assign w3 = w1;
 assign w3 = w2;
 assign w4 = w0;
 assign w4 = w1;
 assign w4 = w2;
 assign w4 = w3;
 assign w5 = w0;
 assign w5 = w1;
 assign w5 = w2;
 assign w5 = w3;
 assign w5 = w4;
 assign w6 = w0;
 assign w6 = w1;
 assign w6 = w2;
 assign w6 = w3;
 assign w6 = w4;
 assign w6 = w5;
 assign w7 = w0;
 assign w7 = w1;
 assign w7 = w2;
 assign w7 = w3;
 assign w7 = w4;
 assign w7 = w5;
 assign w7 = w6;
 vfebcfe v59c87c (
  .v9fb85f(w0)
 );
endmodule

//---- Top entity
module vfebcfe (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vfebcfe_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 1
//---------------------------------------------------

module vfebcfe_vb2eccd (
 output q
);
 //-- Constant bit-1
 assign q = 1'b1;
 
 
endmodule
