// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main #(
 parameter v6672cd = 170
) (
 output [7:0] v62a1d5
);
 localparam p1 = v6672cd;
 wire [0:7] w0;
 assign v62a1d5 = w0;
 vffc517 #(
  .vc5c8ea(p1)
 ) v3de08f (
  .va0aeac(w0)
 );
endmodule

//---- Top entity
module vffc517 #(
 parameter vc5c8ea = 0
) (
 output [7:0] va0aeac
);
 localparam p0 = vc5c8ea;
 wire [0:7] w1;
 assign va0aeac = w1;
 vffc517_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

//---------------------------------------------------
//-- 8-bits-gen-constant
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Generic: 8-bits generic constant (0-255)
//---------------------------------------------------

module vffc517_v465065 #(
 parameter VALUE = 0
) (
 output [7:0] k
);
 assign k = VALUE;
endmodule
