// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main (
 input ve946d7,
 input v8486fd,
 output vb54991,
 output v8c442e,
 output [0:5] vinit
);
 wire w0;
 wire w1;
 assign vb54991 = w0;
 assign w0 = ve946d7;
 assign v8c442e = w1;
 assign w1 = v8486fd;
 assign vinit = 6'b000000;
endmodule

