// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main (
 output vb54991,
 output vfa7327,
 output vdb2924,
 output v7762e3,
 output [0:3] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign vb54991 = w0;
 assign vfa7327 = w1;
 assign vdb2924 = w2;
 assign v7762e3 = w3;
 assign w1 = w0;
 assign w2 = w0;
 assign w2 = w1;
 assign w3 = w0;
 assign w3 = w1;
 assign w3 = w2;
 vfebcfe v59c87c (
  .v9fb85f(w0)
 );
 assign vinit = 4'b0000;
endmodule

//---- Top entity
module vfebcfe (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vfebcfe_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 1
//---------------------------------------------------

module vfebcfe_vb2eccd (
 output q
);
 //-- Constant bit-1
 assign q = 1'b1;
 
 
endmodule
